@startuml ice
actor Alice
actor SignalingServer
actor STUNServer
actor TURNServer
actor Bob

Alice -> Alice: Sammelt Kandidatenadressen
activate Alice
Alice -> SignalingServer: Verbindungsanfrage für Bob
activate SignalingServer
Alice -> SignalingServer: Sendet eigene Kandidatenadressen
deactivate Alice
SignalingServer -> Bob: Anfrage der Kanidatenadressen von Bob
deactivate SignalingServer
activate Bob
Bob -> Bob: Sammelt Kandidatenadressen
Bob --> SignalingServer: Antwort mit Kandidatenadressen
deactivate Bob
activate SignalingServer
SignalingServer --> Alice: Antwort mit Kandidatenadressen von Bob
deactivate SignalingServer
activate Alice
Alice -> Alice: Erstellt Kandidatenpaare
Alice -> Alice: Erstellt Checkliste aus Kandidatenpaaren
Alice -> Alice: Führt Konnektivitätschecks anhand der Checkliste durch
Alice -> Alice: Wählt Kandidatenpaar aus
deactivate Alice


alt Direkte Verbindung
    Alice -> Bob: Sendet Nachricht
    activate Bob
    Bob -> Alice: Sendet Nachricht
    deactivate Bob

else Verbindung über STUN
    Alice -> STUNServer: Sendet STUN-Anfrage
    activate STUNServer
    STUNServer --> Alice: Sendet STUN-Antwort
    deactivate STUNServer
    Bob -> STUNServer: Sendet STUN-Anfrage
    activate STUNServer
    STUNServer --> Bob: Sendet STUN-Antwort
    deactivate STUNServer
    Alice -> Bob: Sendet Nachricht
    Bob -> Alice: Sendet Nachricht

else Verbindung über TURN
    Alice -> TURNServer: Sendet TURN-Anfrage
    activate TURNServer
    TURNServer --> Alice: Sendet TURN-Antwort
    deactivate TURNServer
    Bob -> TURNServer: Sendet TURN-Anfrage
    activate TURNServer
    TURNServer --> Bob: Sendet TURN-Antwort
    deactivate TURNServer
    Alice -> TURNServer: Sendet Nachricht
    activate TURNServer
    TURNServer -> Bob: Sendet Nachricht
    deactivate TURNServer
    Bob -> TURNServer: Sendet Nachricht
    activate TURNServer
    TURNServer -> Alice: Sendet Nachricht
    deactivate TURNServer
end

@enduml