@startuml encryption
actor Alice
actor Bob

group Authentifizierter Diffie-Hellman-Schlüsselaustausch
    
    Alice -> Alice: Erzeugt flüchtiges Schlüsselpaar
    activate Alice
    Alice -> Alice: Signiert flüchtigen öffentlichen Schlüssel
    Alice -> Bob: Sendet flüchtigen öffentlichen Schlüssel und Signatur
    deactivate Alice

    activate Bob
    Bob -> Bob: Verifiziert Signatur des flüchtigen öffentlichen Schlüssels von Alice
    Bob -> Bob: Erzeugt flüchtiges Schlüsselpaar
    Bob -> Bob: Signiert flüchtigen öffentlichen Schlüssel
    Bob -> Alice: Sendet flüchtigen öffentlichen Schlüssel und Signatur
    deactivate Bob
end

group Double Ratchet Algorithmus
    Alice -> Bob: Sendet verschlüsselte Nachricht
    Bob -> Bob: Entschlüsselt Nachricht
end

@enduml